"""deallens_initial_schema

Revision ID: 758f33e133a9
Revises: 
Create Date: 2026-03-29 12:25:20.517543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758f33e133a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('lei', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=2), nullable=True),
    sa.Column('listing_status', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sic_code', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('hq_city', sa.String(), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=False)
    op.create_index(op.f('ix_companies_jurisdiction'), 'companies', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_companies_lei'), 'companies', ['lei'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('market_digest',
    sa.Column('digest_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_themes', sa.JSON(), nullable=True),
    sa.Column('total_deals_tracked', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('digest_id'),
    sa.UniqueConstraint('period', 'period_label', name='uq_digest_period')
    )
    op.create_table('market_news_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('companies_mentioned', sa.JSON(), nullable=True),
    sa.Column('tickers_mentioned', sa.JSON(), nullable=True),
    sa.Column('deal_size_usd', sa.Float(), nullable=True),
    sa.Column('deal_type', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('classification_raw', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    op.create_index(op.f('ix_market_news_items_category'), 'market_news_items', ['category'], unique=False)
    op.create_index(op.f('ix_market_news_items_published_at'), 'market_news_items', ['published_at'], unique=False)
    op.create_table('discovery_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('input_company_id', sa.String(), nullable=False),
    sa.Column('strategy_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['input_company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_discovery_runs_input_company_id'), 'discovery_runs', ['input_company_id'], unique=False)
    op.create_table('drafts',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_index(op.f('ix_drafts_company_id'), 'drafts', ['company_id'], unique=False)
    op.create_table('enrichment_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('revenue_usd', sa.Float(), nullable=True),
    sa.Column('revenue_year', sa.Integer(), nullable=True),
    sa.Column('ebitda_usd', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('net_income_usd', sa.Float(), nullable=True),
    sa.Column('total_assets_usd', sa.Float(), nullable=True),
    sa.Column('total_debt_usd', sa.Float(), nullable=True),
    sa.Column('cash_usd', sa.Float(), nullable=True),
    sa.Column('enterprise_value_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('ev_revenue_multiple', sa.Float(), nullable=True),
    sa.Column('ev_ebitda_multiple', sa.Float(), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('ownership_structure', sa.String(), nullable=True),
    sa.Column('controlling_shareholder', sa.String(), nullable=True),
    sa.Column('controlling_stake_pct', sa.Float(), nullable=True),
    sa.Column('pe_sponsor', sa.String(), nullable=True),
    sa.Column('pe_vintage_year', sa.Integer(), nullable=True),
    sa.Column('strategic_priorities', sa.JSON(), nullable=True),
    sa.Column('recent_acquisitions', sa.JSON(), nullable=True),
    sa.Column('recent_divestitures', sa.JSON(), nullable=True),
    sa.Column('key_products', sa.JSON(), nullable=True),
    sa.Column('geographic_markets', sa.JSON(), nullable=True),
    sa.Column('customer_concentration', sa.Float(), nullable=True),
    sa.Column('top_customers', sa.JSON(), nullable=True),
    sa.Column('top_competitors', sa.JSON(), nullable=True),
    sa.Column('m_and_a_appetite', sa.String(), nullable=True),
    sa.Column('rumored_target', sa.Boolean(), nullable=True),
    sa.Column('rumored_seller', sa.Boolean(), nullable=True),
    sa.Column('activist_present', sa.Boolean(), nullable=True),
    sa.Column('management_change_recent', sa.Boolean(), nullable=True),
    sa.Column('strategic_review_underway', sa.Boolean(), nullable=True),
    sa.Column('coverage_depth', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('discovery_eligible', sa.Boolean(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('gpt_research_raw', sa.Text(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_enrichment_profiles_company_id'), 'enrichment_profiles', ['company_id'], unique=True)
    op.create_table('entity_aliases',
    sa.Column('alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('company_id', 'alias', name='uq_entity_alias')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_company_id'), 'entity_aliases', ['company_id'], unique=False)
    op.create_table('regulatory_predictions',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('buyer_company_id', sa.String(), nullable=False),
    sa.Column('target_company_id', sa.String(), nullable=False),
    sa.Column('overall_risk', sa.String(), nullable=True),
    sa.Column('combined_market_share', sa.Float(), nullable=True),
    sa.Column('hhi_delta', sa.Float(), nullable=True),
    sa.Column('jurisdictions_flagged', sa.JSON(), nullable=True),
    sa.Column('likely_remedies', sa.JSON(), nullable=True),
    sa.Column('expected_timeline_months', sa.Integer(), nullable=True),
    sa.Column('clearance_probability', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_regulatory_predictions_buyer_company_id'), 'regulatory_predictions', ['buyer_company_id'], unique=False)
    op.create_index(op.f('ix_regulatory_predictions_target_company_id'), 'regulatory_predictions', ['target_company_id'], unique=False)
    op.create_table('shortlists',
    sa.Column('shortlist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=True),
    sa.Column('anchor_company_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anchor_company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('shortlist_id')
    )
    op.create_index(op.f('ix_shortlists_anchor_company_id'), 'shortlists', ['anchor_company_id'], unique=False)
    op.create_table('discovery_results',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('candidate_company_id', sa.String(), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('hard_gate', sa.String(), nullable=True),
    sa.Column('dealability_verdict', sa.String(), nullable=True),
    sa.Column('acquisition_route', sa.String(), nullable=True),
    sa.Column('component_scores', sa.JSON(), nullable=True),
    sa.Column('feature_snapshot', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['discovery_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_discovery_results_candidate_company_id'), 'discovery_results', ['candidate_company_id'], unique=False)
    op.create_index(op.f('ix_discovery_results_run_id'), 'discovery_results', ['run_id'], unique=False)
    op.create_table('shortlist_entries',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('shortlist_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['shortlist_id'], ['shortlists.shortlist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('shortlist_id', 'company_id', name='uq_shortlist_entry')
    )
    op.create_index(op.f('ix_shortlist_entries_company_id'), 'shortlist_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_shortlist_entries_shortlist_id'), 'shortlist_entries', ['shortlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlist_entries_shortlist_id'), table_name='shortlist_entries')
    op.drop_index(op.f('ix_shortlist_entries_company_id'), table_name='shortlist_entries')
    op.drop_table('shortlist_entries')
    op.drop_index(op.f('ix_discovery_results_run_id'), table_name='discovery_results')
    op.drop_index(op.f('ix_discovery_results_candidate_company_id'), table_name='discovery_results')
    op.drop_table('discovery_results')
    op.drop_index(op.f('ix_shortlists_anchor_company_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_regulatory_predictions_target_company_id'), table_name='regulatory_predictions')
    op.drop_index(op.f('ix_regulatory_predictions_buyer_company_id'), table_name='regulatory_predictions')
    op.drop_table('regulatory_predictions')
    op.drop_index(op.f('ix_entity_aliases_company_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_enrichment_profiles_company_id'), table_name='enrichment_profiles')
    op.drop_table('enrichment_profiles')
    op.drop_index(op.f('ix_drafts_company_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_discovery_runs_input_company_id'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    op.drop_index(op.f('ix_market_news_items_published_at'), table_name='market_news_items')
    op.drop_index(op.f('ix_market_news_items_category'), table_name='market_news_items')
    op.drop_table('market_news_items')
    op.drop_table('market_digest')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_lei'), table_name='companies')
    op.drop_index(op.f('ix_companies_jurisdiction'), table_name='companies')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
